version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
  pre_build:
    commands:
      - echo 'no dependencies'
      - export ENVIRONMENT=$REACT_APP_ENVIRONMENT
      - export SDK_URL=https://dev.sdk.paytheorystudy.com/$REACT_APP_ENVIRONMENT/index.js
  build:
    commands:
      - sh shell/build_env.sh
      - sh shell/deploy.sh
  post_build:
    commands:
      - echo Build completed on `date`