version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
  pre_build:
    commands:
      - echo 'no dependencies'
  build:
    commands:

  post_build:
    commands:
      - /usr/local/bin/aws s3 cp public s3://secure-tags-lib-$REACT_APP_ENVIRONMENT --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive --cache-control max-age=3
      - echo Build completed on `date`