AWSTemplateFormatVersion: 2010-09-09
Description: Secure Tags Library Deployment
Parameters:
  Partner:
    Type: String
    Description: The environment you're deploying to.
  Stage:
    Type: String
    Description: Library stage to use.
Resources:
  HTMLExampleCodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub 'paytheory-html-demo-${Partner}-${Stage}'
      Description: A website providing hosted fields for Pay Theory SDK
      ServiceRole: 'arn:aws:iam::291752019718:role/pay-theory-code-builder'
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:5.0'
        EnvironmentVariables:
          - Name: PARTNER
            Type: PLAINTEXT
            Value: !Sub '${Partner}'
          - Name: STAGE
            Type: PLAINTEXT
            Value: !Sub '${Stage}'
      Source:
        Location: >-
          https://git-codecommit.us-east-1.amazonaws.com/v1/repos/html-demo
        Type: CODECOMMIT
        BuildSpec: buildspec.yml
      SourceVersion: !Sub 'refs/heads/${Partner}-${Stage}'
      TimeoutInMinutes: 10
  HTMLExamplePipeline:
    DependsOn:
      - HTMLExampleCodeBuild
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub 'paytheory-html-demo-${Partner}-${Stage}'
      RoleArn: >-
        arn:aws:iam::291752019718:role/service-role/AWSCodePipelineServiceRole-paytheory
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                PollForSourceChanges: false
                BranchName: !Sub '${Partner}-${Stage}'
                RepositoryName: html-demo
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              Region: us-east-1
              Namespace: BuildVariables
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub 'paytheory-html-demo-${Partner}-${Stage}'
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: paytheory-static-deployment
  HTMLExampleCloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${Partner}.html.example.${Stage}.com'
        CustomErrorResponses:
          -
            ErrorCachingMinTTL: 10
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: !Sub 'paytheory-sdk-example-${Partner}-${Stage}'
          CachePolicyId: f07eda0f-b830-4ed7-ba09-0bd5504ca2ff
          OriginRequestPolicyId: d1f5d86b-bc1b-44b9-89e9-2d7720fab3b7
          ViewerProtocolPolicy: redirect-to-https
        HttpVersion: http2
        IPV6Enabled: true
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginSSLProtocols:
                - TLSv1.2
            DomainName: paytheory-sdk-example.s3-website-us-east-1.amazonaws.com
            OriginPath: !Sub '/html/${Partner}-${Stage}'
            Id: !Sub 'paytheory-sdk-example-${Partner}-${Stage}'
        ViewerCertificate:
          AcmCertificateArn: !ImportValue 
            'Fn::Sub': pt-environment-html-example-certificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: 'sni-only'
  HTMLExampleRoute53:
    DependsOn:
      - HTMLExampleCloudFront
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !ImportValue 
            'Fn::Sub': 'pt-environment-${Stage}-zone'
      RecordSets:  
        - 
          Name: !Sub '${Partner}.html.example.${Stage}.com'
          Type: A
          AliasTarget: 
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt HTMLExampleCloudFront.DomainName