AWSTemplateFormatVersion: 2010-09-09
Description: product globals
Parameters:
  Partner:
    Type: String
    Description: the partner deployed
  Repository:
    Type: String
    Description: the repository deployed
    Default: 'html-demo'
  Product:
    Type: String
    Description: the product name
    Default: 'html-demo'
  Type:
    Type: String
    Description: the product type
    Default: 'example'
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.html.example.paytheory.com'
      SubjectAlternativeNames: 
        - !Sub '*.html.example.paytheorylab.com'
        - !Sub '*.html.example.paytheorystudy.com'
      ValidationMethod: DNS

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub 'paytheory-sdk-example-${Repository}'
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete
  BucketPolicy:
    DependsOn:
      - S3Bucket
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::paytheory-sdk-example-${Repository}/*'
            Principal: '*'
          - Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::paytheory-sdk-example-${Repository}'
            Principal: '*'    
    
            
  PSCertificate:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "pt-account-${Repository}-certificate"
      Type: String
      Value: !Ref Certificate
      Description: !Sub 'certificate for ${Repository}'
      
  PSS3Bucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "pt-account-${Repository}-bucket"
      Type: String
      Value: !Ref S3Bucket
      Description: !Sub 'bucket for ${Repository}'
      
  PSS3BucketWebsite:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "pt-account-${Repository}-bucket-website"
      Type: String
      Value: !Sub "${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com"
      Description: !Sub 'website for ${Repository} bucket'            
